/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedNotesRouteImport } from './routes/_authed.notes'
import { Route as AuthedPrelaunchRouteImport } from './routes/_authed.prelaunch'
import { Route as AuthedRoadmapRouteImport } from './routes/_authed.roadmap'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotesRoute = AuthedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPrelaunchRoute = AuthedPrelaunchRouteImport.update({
  id: '/prelaunch',
  path: '/prelaunch',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoadmapRoute = AuthedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/notes': typeof AuthedNotesRoute
  '/prelaunch': typeof AuthedPrelaunchRoute
  '/roadmap': typeof AuthedRoadmapRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/notes': typeof AuthedNotesRoute
  '/prelaunch': typeof AuthedPrelaunchRoute
  '/roadmap': typeof AuthedRoadmapRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_authed/notes': typeof AuthedNotesRoute
  '/_authed/prelaunch': typeof AuthedPrelaunchRoute
  '/_authed/roadmap': typeof AuthedRoadmapRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/login' | '/notes' | '/prelaunch' | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/login' | '/notes' | '/prelaunch' | '/roadmap' | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/about'
    | '/login'
    | '/_authed/notes'
    | '/_authed/prelaunch'
    | '/_authed/roadmap'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notes': {
      id: '/_authed/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/prelaunch': {
      id: '/_authed/prelaunch'
      path: '/prelaunch'
      fullPath: '/prelaunch'
      preLoaderRoute: typeof AuthedPrelaunchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roadmap': {
      id: '/_authed/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthedRoadmapRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedNotesRoute: typeof AuthedNotesRoute
  AuthedPrelaunchRoute: typeof AuthedPrelaunchRoute
  AuthedRoadmapRoute: typeof AuthedRoadmapRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedNotesRoute: AuthedNotesRoute,
  AuthedPrelaunchRoute: AuthedPrelaunchRoute,
  AuthedRoadmapRoute: AuthedRoadmapRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
